INCLUDES = -I${TRICK_HOME}/trick_models \
           -I/usr/local/include/hiredis \
           -I$(TOP_DIR)/models/nxbus/include \
           -I$(TOP_DIR)/models/gnc/include \
           -I$(TOP_DIR)/models/dm/include \
           -I$(TOP_DIR)/models/cad/include \
           -I$(TOP_DIR)/models/math/include \
           -I$(TOP_DIR)/models/aux/include \
           -I$(TOP_DIR)/models/sensor/include \
           -I$(TOP_DIR)/models/driver/include \
           -I$(TOP_DIR)/models/icf/include \
           -I$(TOP_DIR)/models/equipment_protocol/include \
           -I$(TOP_DIR)/models/flight_events/include